name: Checkout
on: [workflow_dispatch]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a
            - uses: actions/checkout@v4
            - name: List Fiels After
              run: ls -a 



