name: Checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List files Before
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add orgin "https://$GITHUB_ACTOR:${{ secerts.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Fiels After
              run: ls -a 



